### ISSUE TITLE
windows platform: unresolved DLL dependency (libomp.dll): causing "multiarray numpy extension module failed" 

### ISSUE THREAD

**Issue by 4FH** [conda-forge/flang-feedstock#11]
1. Both flang.dll and flangrti.dll currently(libflang-5.0.0-vc14_20180101) reference libomp.dll
2. ompstub.dll that provided in package is of no use

Solution: either: 1. modify json to include dependency for conda-forge/openmp
                          2. Rebuild(?) flang/flangrti.dll removing dependency on libomp.dll

Currently conda-forge/numpy won't import on Windows because of this , throwing dreaded "Importing the multiarray numpy extension module failed." and "DLL load failed". 
Chain of error propagation is:  numpy<-openblas.dll<-flang/flangrti.dll<-(absence of libomp.dll)

**Comment by xoviat** [comment]
Thanks for tracing this! I'm going to go ahead and add the dependency for libflang, and then we can later discuss pushing the dependency upstream to OpenBLAS and every other project that flang compiles.
