### ISSUE TITLE
Change upstream to llvm-monorepo

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/flang-feedstock#15]
Flang is scheduled to be [included](https://lists.llvm.org/pipermail/llvm-dev/2019-December/137661.html) into the llvm-monorepo. This should make windows-compatibility much easier to achieve without having to carry patches in https://github.com/isuruf/flang, I hope.

Once that happens (plan is to be released with llvm 10.0 in Feb/March), the upstream should switch. Or maybe make a separate "flangdev" feedstock to mirror the naming of [clangdev](https://github.com/conda-forge/clangdev-feedstock) vs. clang?

**Comment by isuruf** [comment]
f18 is only a parser and semantic analyzer and doesn't have a code generator yet, so there's no point packaging f18.

**Comment by h-vetinari** [comment]
OK, guess I got carried away with the email talking about flang, but overlooking that it actually only means f18. Sorry for the noise.
