### ISSUE TITLE
Rebuild for LLVM 11.1?

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/flang-feedstock#21]
Hey @xoviat 

I'm trying out flang 11 in https://github.com/conda-forge/openblas-feedstock/pull/130 and it's hitting https://github.com/conda-forge/llvmdev-feedstock/issues/117 because the fix for that only landed in conda-forge for llvmdev 11.1. I could of course try to backport that fix (assuming the other llvmdev-maintainers agree), but since 11.0 had an unintentional ABI-break (necessitating 11.1), I was wondering if the better approach is to rebuild flang for 11.1?

It's possible (or even likely) that the ABI break is irrelevant for flang itself, but I wanted to ask at least.

CC @isuruf

**Comment by h-vetinari** [comment]
@isuruf, I'd raise a PR here, but since this points to @xoviat's fork, I'm not sure what would need to be done for the sources.

Alternatively, would you be fine with me backporting https://github.com/conda-forge/llvmdev-feedstock/pull/118 to the llvmdev 11.0 builds?

**Comment by isuruf** [comment]
We can just rebuild with llvm 11.1

**Comment by h-vetinari** [comment]
Closing as obsolete
