### ISSUE TITLE
make flang a cross-compiler

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/flang-feedstock#63]
From discussion in #61; this already came up in #28, where we descoped this at the time. This question is about how to do this practically.

Main question I see is how we want to name the feedstocks:
1. flang-feedstock for implementation; flang-activation-feedstock for activation
1. flang-impl-feedstock for implementation; flang-feedstock for activation

The GCC compilers follow more 1. (ctng-compilers & ctng-compiler-activation), but gfortran on osx follows more 2. (gfortran_impl_osx-64 & gfortran_osx-64). I don't really mind either way.

It would probably be convenient to do this as of flang 19, because then we don't have to deal with `fortran_main` (https://github.com/llvm/llvm-project/commit/8d5386669ed63548daf1bee415596582d6d78d7d), but if we could do 18 already, that would probably help the emscripten-folks.

Any preferences for naming @isuruf?

**Comment by isuruf** [comment]
I prefer 1.

**Comment by h-vetinari** [comment]
OK, thanks for the quick response. Do you have a preference to try 18 first, or go straight to 19?

**Comment by isuruf** [comment]
Let's go straight to 19

**Comment by h-vetinari** [comment]
Got a PR to staged recipes: https://github.com/conda-forge/staged-recipes/pull/27470
